### ISSUE TITLE
https://download.vscodium.com/debs is now inaccessible

### ISSUE THREAD

**Issue by RadxaYuntian** [VSCodium/vscodium.github.io#85] opened 2024-06-04 07:43 UTC
Currently we use https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs as a workaround.

**Comment by daiyam** [comment] 2024-06-04 09:06
Duplicate of https://github.com/VSCodium/vscodium/issues/1910

**Closed by daiyam** 2024-06-04 09:06 UTC

**Comment by daiyam** [comment] 2024-06-04 10:08
No because gitlab has stricter limits which the CDN resolve. If the gitlab limits are reached, it would limit us to push new updates.
